apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbvisittkortfs
  namespace: pto
  labels:
    team: pto
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2024.11.12_09.35-97ae4c05891f
  port: 8080
  ingresses:
    - https://veilarbvisittkortfs.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  gcp:
    buckets:
      - name: veilarbvisittkortfs-prod
        cascadingDelete: false
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  env:
    - name: JSON_CONFIG
      value: >
        {
          "cors": {
            "origin": [
              "https://veilarbpersonflate.intern.nav.no",
              "https://arbeidssokerregistrering.intern.nav.no",
              "https://arbeidssokerregistrering-for-veileder.intern.nav.no"
            ]
          },
          "header": {
              "corp": {
              "policy": "cross-origin"
              }
          },
          "gcs": {
            "bucketName": "veilarbvisittkortfs-prod"
          }
        }
