apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbvisittkortfs
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2022.08.31_14.20-714de2440612
  port: 8080
  ingresses:
    - https://veilarbvisittkortfs.dev.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  gcp:
    buckets:
      - name: veilarbvisittkortfs-dev
        cascadingDelete: false
  env:
    - name: GCS_BUCKET_NAME
      value: veilarbvisittkortfs-dev
    - name: CORS_DOMAIN
      value: "*"
