name: Deploy til Q1
on:
    workflow_dispatch:

jobs:
    build:
        name: Build and sync project to q1
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'
            - run: npm ci --legacy-peer-deps
            - run: npm run test
            - run: npm run build
              env:
                  PUBLIC_URL: https://veilarbvisittkortfs.dev.intern.nav.no
            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v0
              with:
                  credentials_json: ${{ secrets.GCS_SA_KEY_DEV }}
            - uses: google-github-actions/setup-gcloud@v0
            - name: Upload files to GCS
              run: gsutil -m rsync -r build gs://veilarbvisittkortfs-dev
