name: Deploy to dev
run-name: Deploy to dev ${{ github.ref_name }} by @${{ github.actor }}
on:
    workflow_dispatch:
    push:
        branches:
            - master
env:
    CI: true
    TZ: Europe/Amsterdam

jobs:
  deploy-dev:
    name: Deploy to dev
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy.yml
    with:
      bucket: veilarbvisittkortfs-dev
      buildCommand: 'npm run build:dev'
      envName: 'dev'
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
