name: Deploy to dev
run-name: Deploy to dev ${{ github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # ratchet:actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Run tests
        run: npm run test

      - name: Build application
        run: npm run build:dev

      - name: Upload to CDN
        uses: nais/deploy/actions/cdn-upload/v2@823ec9b7e305ce7cf911d0f9a25f7da9d7486cf2 # ratchet:nais/deploy/actions/cdn-upload/v2@master
        with:
          team: poao
          source: ./build/
          destination: /veilarbvisittkortfs-dev/

      - name: Set special cache for asset-manifest.json
        shell: bash
        run: |
          gcloud storage objects update "gs://${BUCKET_NAME}/poao/veilarbvisittkortfs-dev/build/asset-manifest.json" --cache-control="public, max-age=120, stale-while-revalidate=1800, stale-if-error=600"
