name: Deploy to dev
run-name: Deploy to dev ${{ github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1

      - name: Install pnpm
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # ratchet:pnpm/setup@v2.0.2
        with:
          install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
        env:
          pnpm_config__auth: '{"https://npm.pkg.github.com":{"@navikt":{"authToken":"${{ secrets.READER_TOKEN }}"}}}'

      - name: Run tests
        run: pnpm test

      - name: Build application
        run: pnpm build:dev

      - name: Upload to CDN
        uses: nais/deploy/actions/cdn-upload/v2@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # ratchet:nais/deploy/actions/cdn-upload/v2@master
        with:
          team: poao
          source: ./build/
          destination: /veilarbvisittkortfs-dev/

      - name: Set special cache for asset-manifest.json
        shell: bash
        run: |
          gcloud storage objects update "gs://${BUCKET_NAME}/poao/veilarbvisittkortfs-dev/build/asset-manifest.json" --cache-control="public, max-age=120, stale-while-revalidate=1800, stale-if-error=600"
