name: Deploy to prod
on:
    push:
        branches:
            - master
env:
    CI: true
    TZ: Europe/Amsterdam

jobs:
  deploy-dev:
    name: Deploy to prod
    permissions:
      id-token: write
    uses: ./.github/workflows/deploy.yml
    with:
      bucket: veilarbvisittkortfs-prod
      buildCommand: 'npm run build'
      envName: 'prod'
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
