name: paoa frontend container dev

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/poao-frontend-container-dev.yaml'
      - '.nais/nais-dev.yaml'
  workflow_dispatch:

concurrency:
  group: poao_frontend_container_dev
  cancel-in-progress: true

env:
  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: deploy gcp dev
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml
