name: paoa frontend container dev

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/poao-frontend-container-dev.yaml'
      - '.nais/nais-dev.yaml'
  workflow_dispatch:

concurrency:
  group: poao_frontend_container_dev
  cancel-in-progress: true

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: deploy gcp dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml
