name: GitHub pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  update-gh-pages:
    name: Update GitHub pages
    environment:
      name: github-pages
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
      - name: Install pnpm
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # ratchet:pnpm/setup@v2.0.2
        with:
          install: false
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
        env:
          pnpm_config__auth: '{"https://npm.pkg.github.com":{"@navikt":{"authToken":"${{ secrets.READER_TOKEN }}"}}}'
      - name: Build mock application
        run: pnpm run build:mock
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # ratchet:actions/upload-pages-artifact@v5.0.0
        with:
          path: ./build
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # ratchet:actions/deploy-pages@v5.0.0
